package com.ys.data.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 3; // 数据库升级

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        GoodsBeanDao.createTable(db, ifNotExists);
        McGoodsBeanDao.createTable(db, ifNotExists);
        McParamsBeanDao.createTable(db, ifNotExists);
        McStatusBeanDao.createTable(db, ifNotExists);
        McAdminBeanDao.createTable(db, ifNotExists);
        PromotionBeanDao.createTable(db, ifNotExists);
        SaleListBeanDao.createTable(db, ifNotExists);
        AdvBeanDao.createTable(db, ifNotExists);

    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        GoodsBeanDao.dropTable(db, ifExists);
        McGoodsBeanDao.dropTable(db, ifExists);
        McParamsBeanDao.dropTable(db, ifExists);
        McStatusBeanDao.dropTable(db, ifExists);
        McAdminBeanDao.dropTable(db, ifExists);
        PromotionBeanDao.dropTable(db, ifExists);
        SaleListBeanDao.dropTable(db, ifExists);
        AdvBeanDao.dropTable(db, ifExists);

    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            // 商品表添加字段
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
             if (oldVersion == 1 && newVersion == 2) {
                 db.execSQL("ALTER TABLE goods ADD COLUMN GD_KEYWORD TEXT");
             } else if (oldVersion == 1 && newVersion == 3) {
                 db.execSQL("ALTER TABLE goods ADD COLUMN GD_KEYWORD TEXT");
                 db.execSQL("ALTER TABLE mcstatus ADD COLUMN mc_isbiller LONG");
                 db.execSQL("ALTER TABLE mcstatus ADD COLUMN mc_isuppos LONG");
                 db.execSQL("ALTER TABLE mcstatus ADD COLUMN mc_iswxpay LONG");
                 db.execSQL("ALTER TABLE mcstatus ADD COLUMN mc_isalipay LONG");

             } else if (oldVersion == 2 && newVersion == 3) {
                 db.execSQL("ALTER TABLE mcstatus ADD COLUMN mc_isbiller LONG");
                 db.execSQL("ALTER TABLE mcstatus ADD COLUMN mc_isuppos LONG");
                 db.execSQL("ALTER TABLE mcstatus ADD COLUMN mc_iswxpay LONG");
                 db.execSQL("ALTER TABLE mcstatus ADD COLUMN mc_isalipay LONG");

             }
            //onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(GoodsBeanDao.class);
        registerDaoClass(McGoodsBeanDao.class);
        registerDaoClass(McParamsBeanDao.class);
        registerDaoClass(McStatusBeanDao.class);
        registerDaoClass(McAdminBeanDao.class);
        registerDaoClass(PromotionBeanDao.class);
        registerDaoClass(SaleListBeanDao.class);
        registerDaoClass(AdvBeanDao.class);

    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
