package com.ys.data.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ys.data.bean.GoodsBean;
import com.ys.data.bean.McGoodsBean;
import com.ys.data.bean.McParamsBean;
import com.ys.data.bean.McStatusBean;
import com.ys.data.bean.McAdminBean;
import com.ys.data.bean.PromotionBean;
import com.ys.data.bean.SaleListBean;

import com.ys.data.dao.GoodsBeanDao;
import com.ys.data.dao.McGoodsBeanDao;
import com.ys.data.dao.McParamsBeanDao;
import com.ys.data.dao.McStatusBeanDao;
import com.ys.data.dao.McAdminBeanDao;
import com.ys.data.dao.PromotionBeanDao;
import com.ys.data.dao.SaleListBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig goodsBeanDaoConfig;
    private final DaoConfig mcGoodsBeanDaoConfig;
    private final DaoConfig mcParamsBeanDaoConfig;
    private final DaoConfig mcStatusBeanDaoConfig;
    private final DaoConfig mcAdminBeanDaoConfig;
    private final DaoConfig promotionBeanDaoConfig;
    private final DaoConfig saleListBeanDaoConfig;

    private final GoodsBeanDao goodsBeanDao;
    private final McGoodsBeanDao mcGoodsBeanDao;
    private final McParamsBeanDao mcParamsBeanDao;
    private final McStatusBeanDao mcStatusBeanDao;
    private final McAdminBeanDao mcAdminBeanDao;
    private final PromotionBeanDao promotionBeanDao;
    private final SaleListBeanDao saleListBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        goodsBeanDaoConfig = daoConfigMap.get(GoodsBeanDao.class).clone();
        goodsBeanDaoConfig.initIdentityScope(type);

        mcGoodsBeanDaoConfig = daoConfigMap.get(McGoodsBeanDao.class).clone();
        mcGoodsBeanDaoConfig.initIdentityScope(type);

        mcParamsBeanDaoConfig = daoConfigMap.get(McParamsBeanDao.class).clone();
        mcParamsBeanDaoConfig.initIdentityScope(type);

        mcStatusBeanDaoConfig = daoConfigMap.get(McStatusBeanDao.class).clone();
        mcStatusBeanDaoConfig.initIdentityScope(type);

        mcAdminBeanDaoConfig = daoConfigMap.get(McAdminBeanDao.class).clone();
        mcAdminBeanDaoConfig.initIdentityScope(type);

        promotionBeanDaoConfig = daoConfigMap.get(PromotionBeanDao.class).clone();
        promotionBeanDaoConfig.initIdentityScope(type);

        saleListBeanDaoConfig = daoConfigMap.get(SaleListBeanDao.class).clone();
        saleListBeanDaoConfig.initIdentityScope(type);

        goodsBeanDao = new GoodsBeanDao(goodsBeanDaoConfig, this);
        mcGoodsBeanDao = new McGoodsBeanDao(mcGoodsBeanDaoConfig, this);
        mcParamsBeanDao = new McParamsBeanDao(mcParamsBeanDaoConfig, this);
        mcStatusBeanDao = new McStatusBeanDao(mcStatusBeanDaoConfig, this);
        mcAdminBeanDao = new McAdminBeanDao(mcAdminBeanDaoConfig, this);
        promotionBeanDao = new PromotionBeanDao(promotionBeanDaoConfig, this);
        saleListBeanDao = new SaleListBeanDao(saleListBeanDaoConfig, this);

        registerDao(GoodsBean.class, goodsBeanDao);
        registerDao(McGoodsBean.class, mcGoodsBeanDao);
        registerDao(McParamsBean.class, mcParamsBeanDao);
        registerDao(McStatusBean.class, mcStatusBeanDao);
        registerDao(McAdminBean.class, mcAdminBeanDao);
        registerDao(PromotionBean.class, promotionBeanDao);
        registerDao(SaleListBean.class, saleListBeanDao);
    }
    
    public void clear() {
        goodsBeanDaoConfig.getIdentityScope().clear();
        mcGoodsBeanDaoConfig.getIdentityScope().clear();
        mcParamsBeanDaoConfig.getIdentityScope().clear();
        mcStatusBeanDaoConfig.getIdentityScope().clear();
        mcAdminBeanDaoConfig.getIdentityScope().clear();
        promotionBeanDaoConfig.getIdentityScope().clear();
        saleListBeanDaoConfig.getIdentityScope().clear();
    }

    public GoodsBeanDao getGoodsBeanDao() {
        return goodsBeanDao;
    }

    public McGoodsBeanDao getMcGoodsBeanDao() {
        return mcGoodsBeanDao;
    }

    public McParamsBeanDao getMcParamsBeanDao() {
        return mcParamsBeanDao;
    }

    public McStatusBeanDao getMcStatusBeanDao() {
        return mcStatusBeanDao;
    }

    public McAdminBeanDao getMcAdminBeanDao() {
        return mcAdminBeanDao;
    }

    public PromotionBeanDao getPromotionBeanDao() {
        return promotionBeanDao;
    }

    public SaleListBeanDao getSaleListBeanDao() {
        return saleListBeanDao;
    }

}
