package com.ys.data.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.ys.data.bean.McParamsBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table mcparams.
*/
public class McParamsBeanDao extends AbstractDao<McParamsBean, String> {

    public static final String TABLENAME = "mcparams";

    /**
     * Properties of entity McParamsBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Pcode = new Property(0, String.class, "pcode", true, "PCODE");
        public final static Property Pvalue = new Property(1, String.class, "pvalue", false, "PVALUE");
    };


    public McParamsBeanDao(DaoConfig config) {
        super(config);
    }
    
    public McParamsBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'mcparams' (" + //
                "'PCODE' TEXT PRIMARY KEY NOT NULL ," + // 0: pcode
                "'PVALUE' TEXT);"); // 1: pvalue
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'mcparams'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, McParamsBean entity) {
        stmt.clearBindings();
 
        String pcode = entity.getPcode();
        if (pcode != null) {
            stmt.bindString(1, pcode);
        }
 
        String pvalue = entity.getPvalue();
        if (pvalue != null) {
            stmt.bindString(2, pvalue);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public McParamsBean readEntity(Cursor cursor, int offset) {
        McParamsBean entity = new McParamsBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // pcode
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // pvalue
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, McParamsBean entity, int offset) {
        entity.setPcode(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setPvalue(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(McParamsBean entity, long rowId) {
        return entity.getPcode();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(McParamsBean entity) {
        if(entity != null) {
            return entity.getPcode();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
