package com.ys.data.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.ys.ui.utils.ImageUtils;
import com.ys.ui.utils.PropertyUtils;

/**
 * Entity mapped to table adv.
 */
public class AdvBean {

    private String ai_id;
    private String ai_file_id;
    private String ai_file_name;
    private String ai_type;
    private String ai_gd_no;

    public AdvBean() {
    }

    public AdvBean(String ai_id) {
        this.ai_id = ai_id;
    }

    public AdvBean(String ai_id, String ai_file_id, String ai_file_name, String ai_type, String ai_gd_no) {
        this.ai_id = ai_id;
        this.ai_file_id = ai_file_id;
        this.ai_file_name = ai_file_name;
        this.ai_type = ai_type;
        this.ai_gd_no = ai_gd_no;
    }

    public String getAi_id() {
        return ai_id;
    }

    public void setAi_id(String ai_id) {
        this.ai_id = ai_id;
    }

    public String getAi_file_id() {
        return ai_file_id;
    }
    public String getFileUrl() {
        return PropertyUtils.getInstance().getFastDfsUrl() + ImageUtils.getImageUrl(ai_file_id);
    }

    public void setAi_file_id(String ai_file_id) {
        this.ai_file_id = ai_file_id;
    }

    public String getAi_file_name() {
        return ai_file_name;
    }

    public void setAi_file_name(String ai_file_name) {
        this.ai_file_name = ai_file_name;
    }

    public String getAi_type() {
        return ai_type;
    }

    public void setAi_type(String ai_type) {
        this.ai_type = ai_type;
    }

    public String getAi_gd_no() {
        return ai_gd_no;
    }

    public void setAi_gd_no(String ai_gd_no) {
        this.ai_gd_no = ai_gd_no;
    }

}
