package com.ys.data.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table goods.
 */
public class GoodsBean  implements Serializable  {

    private String gd_no;
    private String gd_code;
    private String gd_short_name;
    private String gd_name;
    private String gd_type;
    private String gd_ty_class;
    private String gd_pm_class;
    private String gd_nm_class;
    private String gd_approve_code;
    private String gd_spec;
    private String gd_brand;
    private String gd_manufacturer;
    private String gd_saleunit;
    private String gd_barcode;
    private Long gd_sale_price;
    private Long gd_disc_price;
    private Long gd_vip_price;
    private Long gd_score_price;
    private Long gd_supplier;
    private String gd_img1;
    private String gd_img2;
    private String gd_img3;
    private String gd_img4;
    private String gd_img_s;
    private String gd_instruction_file;
    private String gd_desc;
    private String gd_url;
    private String gd_desc1;
    private String gd_desc2;
    private String gd_desc3;
    private String gd_desc4;
    private String gd_desc5;
    private String mer_no;
    private String remark;
    private String addtime;
    private String updatetime;
    private String gd_keyword;

    public GoodsBean() {
    }

    public GoodsBean(String gd_no) {
        this.gd_no = gd_no;
    }

    public GoodsBean(String gd_no, String gd_code, String gd_short_name, String gd_name, String gd_type, String gd_ty_class, String gd_pm_class, String gd_nm_class, String gd_approve_code, String gd_spec, String gd_brand, String gd_manufacturer, String gd_saleunit, String gd_barcode, Long gd_sale_price, Long gd_disc_price, Long gd_vip_price, Long gd_score_price, Long gd_supplier, String gd_img1, String gd_img2, String gd_img3, String gd_img4, String gd_img_s, String gd_instruction_file, String gd_desc, String gd_url, String gd_desc1, String gd_desc2, String gd_desc3, String gd_desc4, String gd_desc5, String mer_no, String remark, String addtime, String updatetime, String gd_keyword) {
        this.gd_no = gd_no;
        this.gd_code = gd_code;
        this.gd_short_name = gd_short_name;
        this.gd_name = gd_name;
        this.gd_type = gd_type;
        this.gd_ty_class = gd_ty_class;
        this.gd_pm_class = gd_pm_class;
        this.gd_nm_class = gd_nm_class;
        this.gd_approve_code = gd_approve_code;
        this.gd_spec = gd_spec;
        this.gd_brand = gd_brand;
        this.gd_manufacturer = gd_manufacturer;
        this.gd_saleunit = gd_saleunit;
        this.gd_barcode = gd_barcode;
        this.gd_sale_price = gd_sale_price;
        this.gd_disc_price = gd_disc_price;
        this.gd_vip_price = gd_vip_price;
        this.gd_score_price = gd_score_price;
        this.gd_supplier = gd_supplier;
        this.gd_img1 = gd_img1;
        this.gd_img2 = gd_img2;
        this.gd_img3 = gd_img3;
        this.gd_img4 = gd_img4;
        this.gd_img_s = gd_img_s;
        this.gd_instruction_file = gd_instruction_file;
        this.gd_desc = gd_desc;
        this.gd_url = gd_url;
        this.gd_desc1 = gd_desc1;
        this.gd_desc2 = gd_desc2;
        this.gd_desc3 = gd_desc3;
        this.gd_desc4 = gd_desc4;
        this.gd_desc5 = gd_desc5;
        this.mer_no = mer_no;
        this.remark = remark;
        this.addtime = addtime;
        this.updatetime = updatetime;
        this.gd_keyword = gd_keyword;
    }

    public String getGd_no() {
        return gd_no;
    }

    public void setGd_no(String gd_no) {
        this.gd_no = gd_no;
    }

    public String getGd_code() {
        return gd_code;
    }

    public void setGd_code(String gd_code) {
        this.gd_code = gd_code;
    }

    public String getGd_short_name() {
        return gd_short_name;
    }

    public void setGd_short_name(String gd_short_name) {
        this.gd_short_name = gd_short_name;
    }

    public String getGd_name() {
        return gd_name;
    }

    public void setGd_name(String gd_name) {
        this.gd_name = gd_name;
    }

    public String getGd_type() {
        return gd_type;
    }

    public void setGd_type(String gd_type) {
        this.gd_type = gd_type;
    }

    public String getGd_ty_class() {
        return gd_ty_class;
    }

    public void setGd_ty_class(String gd_ty_class) {
        this.gd_ty_class = gd_ty_class;
    }

    public String getGd_pm_class() {
        return gd_pm_class;
    }

    public void setGd_pm_class(String gd_pm_class) {
        this.gd_pm_class = gd_pm_class;
    }

    public String getGd_nm_class() {
        return gd_nm_class;
    }

    public void setGd_nm_class(String gd_nm_class) {
        this.gd_nm_class = gd_nm_class;
    }

    public String getGd_approve_code() {
        return gd_approve_code;
    }

    public void setGd_approve_code(String gd_approve_code) {
        this.gd_approve_code = gd_approve_code;
    }

    public String getGd_spec() {
        return gd_spec;
    }

    public void setGd_spec(String gd_spec) {
        this.gd_spec = gd_spec;
    }

    public String getGd_brand() {
        return gd_brand;
    }

    public void setGd_brand(String gd_brand) {
        this.gd_brand = gd_brand;
    }

    public String getGd_manufacturer() {
        return gd_manufacturer;
    }

    public void setGd_manufacturer(String gd_manufacturer) {
        this.gd_manufacturer = gd_manufacturer;
    }

    public String getGd_saleunit() {
        return gd_saleunit;
    }

    public void setGd_saleunit(String gd_saleunit) {
        this.gd_saleunit = gd_saleunit;
    }

    public String getGd_barcode() {
        return gd_barcode;
    }

    public void setGd_barcode(String gd_barcode) {
        this.gd_barcode = gd_barcode;
    }

    public Long getGd_sale_price() {
        return gd_sale_price;
    }

    public void setGd_sale_price(Long gd_sale_price) {
        this.gd_sale_price = gd_sale_price;
    }

    public Long getGd_disc_price() {
        return gd_disc_price;
    }

    public void setGd_disc_price(Long gd_disc_price) {
        this.gd_disc_price = gd_disc_price;
    }

    public Long getGd_vip_price() {
        return gd_vip_price;
    }

    public void setGd_vip_price(Long gd_vip_price) {
        this.gd_vip_price = gd_vip_price;
    }

    public Long getGd_score_price() {
        return gd_score_price;
    }

    public void setGd_score_price(Long gd_score_price) {
        this.gd_score_price = gd_score_price;
    }

    public Long getGd_supplier() {
        return gd_supplier;
    }

    public void setGd_supplier(Long gd_supplier) {
        this.gd_supplier = gd_supplier;
    }

    public String getGd_img1() {
        return gd_img1;
    }

    public void setGd_img1(String gd_img1) {
        this.gd_img1 = gd_img1;
    }

    public String getGd_img2() {
        return gd_img2;
    }

    public void setGd_img2(String gd_img2) {
        this.gd_img2 = gd_img2;
    }

    public String getGd_img3() {
        return gd_img3;
    }

    public void setGd_img3(String gd_img3) {
        this.gd_img3 = gd_img3;
    }

    public String getGd_img4() {
        return gd_img4;
    }

    public void setGd_img4(String gd_img4) {
        this.gd_img4 = gd_img4;
    }

    public String getGd_img_s() {
        return gd_img_s;
    }

    public void setGd_img_s(String gd_img_s) {
        this.gd_img_s = gd_img_s;
    }

    public String getGd_instruction_file() {
        return gd_instruction_file;
    }

    public void setGd_instruction_file(String gd_instruction_file) {
        this.gd_instruction_file = gd_instruction_file;
    }

    public String getGd_desc() {
        return gd_desc;
    }

    public void setGd_desc(String gd_desc) {
        this.gd_desc = gd_desc;
    }

    public String getGd_url() {
        return gd_url;
    }

    public void setGd_url(String gd_url) {
        this.gd_url = gd_url;
    }

    public String getGd_desc1() {
        return gd_desc1;
    }

    public void setGd_desc1(String gd_desc1) {
        this.gd_desc1 = gd_desc1;
    }

    public String getGd_desc2() {
        return gd_desc2;
    }

    public void setGd_desc2(String gd_desc2) {
        this.gd_desc2 = gd_desc2;
    }

    public String getGd_desc3() {
        return gd_desc3;
    }

    public void setGd_desc3(String gd_desc3) {
        this.gd_desc3 = gd_desc3;
    }

    public String getGd_desc4() {
        return gd_desc4;
    }

    public void setGd_desc4(String gd_desc4) {
        this.gd_desc4 = gd_desc4;
    }

    public String getGd_desc5() {
        return gd_desc5;
    }

    public void setGd_desc5(String gd_desc5) {
        this.gd_desc5 = gd_desc5;
    }

    public String getMer_no() {
        return mer_no;
    }

    public void setMer_no(String mer_no) {
        this.mer_no = mer_no;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getAddtime() {
        return addtime;
    }

    public void setAddtime(String addtime) {
        this.addtime = addtime;
    }

    public String getUpdatetime() {
        return updatetime;
    }

    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime;
    }

    public String getGd_keyword() {
        return gd_keyword;
    }

    public void setGd_keyword(String gd_keyword) {
        this.gd_keyword = gd_keyword;
    }

}
