package com.ys.data.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table mcadmin.
 */
public class McAdminBean {

    private String u_no;
    private String u_pwd;

    public McAdminBean() {
    }

    public McAdminBean(String u_no) {
        this.u_no = u_no;
    }

    public McAdminBean(String u_no, String u_pwd) {
        this.u_no = u_no;
        this.u_pwd = u_pwd;
    }

    public String getU_no() {
        return u_no;
    }

    public void setU_no(String u_no) {
        this.u_no = u_no;
    }

    public String getU_pwd() {
        return u_pwd;
    }

    public void setU_pwd(String u_pwd) {
        this.u_pwd = u_pwd;
    }

}
