package com.ys.data.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table mcgoods.
 */
public class McGoodsBean {

    private Integer mg_id;
    private String mc_no;
    private String mg_channo;
    private String gd_id;
    private String gd_no;
    private String gd_type;
    private String gd_approve_code;
    private String gd_batch_no;
    private String gd_des_code;
    private java.util.Date gd_mf_date;
    private java.util.Date gd_exp_date;
    private Integer mg_gvol;
    private Integer mg_gnum;
    private Integer prePrice;
    private Integer scorePrice;
    private Integer mg_vip_price;
    private Integer mg_price;
    private Integer chanStatus;
    private java.util.Date addtime;
    private java.util.Date updatetime;

    public McGoodsBean() {
    }

    public McGoodsBean(Integer mg_id) {
        this.mg_id = mg_id;
    }

    public McGoodsBean(Integer mg_id, String mc_no, String mg_channo, String gd_id, String gd_no, String gd_type, String gd_approve_code, String gd_batch_no, String gd_des_code, java.util.Date gd_mf_date, java.util.Date gd_exp_date, Integer mg_gvol, Integer mg_gnum, Integer prePrice, Integer scorePrice, Integer mg_vip_price, Integer mg_price, Integer chanStatus, java.util.Date addtime, java.util.Date updatetime) {
        this.mg_id = mg_id;
        this.mc_no = mc_no;
        this.mg_channo = mg_channo;
        this.gd_id = gd_id;
        this.gd_no = gd_no;
        this.gd_type = gd_type;
        this.gd_approve_code = gd_approve_code;
        this.gd_batch_no = gd_batch_no;
        this.gd_des_code = gd_des_code;
        this.gd_mf_date = gd_mf_date;
        this.gd_exp_date = gd_exp_date;
        this.mg_gvol = mg_gvol;
        this.mg_gnum = mg_gnum;
        this.prePrice = prePrice;
        this.scorePrice = scorePrice;
        this.mg_vip_price = mg_vip_price;
        this.mg_price = mg_price;
        this.chanStatus = chanStatus;
        this.addtime = addtime;
        this.updatetime = updatetime;
    }

    public Integer getMg_id() {
        return mg_id;
    }

    public void setMg_id(Integer mg_id) {
        this.mg_id = mg_id;
    }

    public String getMc_no() {
        return mc_no;
    }

    public void setMc_no(String mc_no) {
        this.mc_no = mc_no;
    }

    public String getMg_channo() {
        return mg_channo;
    }

    public void setMg_channo(String mg_channo) {
        this.mg_channo = mg_channo;
    }

    public String getGd_id() {
        return gd_id;
    }

    public void setGd_id(String gd_id) {
        this.gd_id = gd_id;
    }

    public String getGd_no() {
        return gd_no;
    }

    public void setGd_no(String gd_no) {
        this.gd_no = gd_no;
    }

    public String getGd_type() {
        return gd_type;
    }

    public void setGd_type(String gd_type) {
        this.gd_type = gd_type;
    }

    public String getGd_approve_code() {
        return gd_approve_code;
    }

    public void setGd_approve_code(String gd_approve_code) {
        this.gd_approve_code = gd_approve_code;
    }

    public String getGd_batch_no() {
        return gd_batch_no;
    }

    public void setGd_batch_no(String gd_batch_no) {
        this.gd_batch_no = gd_batch_no;
    }

    public String getGd_des_code() {
        return gd_des_code;
    }

    public void setGd_des_code(String gd_des_code) {
        this.gd_des_code = gd_des_code;
    }

    public java.util.Date getGd_mf_date() {
        return gd_mf_date;
    }

    public void setGd_mf_date(java.util.Date gd_mf_date) {
        this.gd_mf_date = gd_mf_date;
    }

    public java.util.Date getGd_exp_date() {
        return gd_exp_date;
    }

    public void setGd_exp_date(java.util.Date gd_exp_date) {
        this.gd_exp_date = gd_exp_date;
    }

    public Integer getMg_gvol() {
        return mg_gvol;
    }

    public void setMg_gvol(Integer mg_gvol) {
        this.mg_gvol = mg_gvol;
    }

    public Integer getMg_gnum() {
        return mg_gnum;
    }

    public void setMg_gnum(Integer mg_gnum) {
        this.mg_gnum = mg_gnum;
    }

    public Integer getPrePrice() {
        return prePrice;
    }

    public void setPrePrice(Integer prePrice) {
        this.prePrice = prePrice;
    }

    public Integer getScorePrice() {
        return scorePrice;
    }

    public void setScorePrice(Integer scorePrice) {
        this.scorePrice = scorePrice;
    }

    public Integer getMg_vip_price() {
        return mg_vip_price;
    }

    public void setMg_vip_price(Integer mg_vip_price) {
        this.mg_vip_price = mg_vip_price;
    }

    public Integer getMg_price() {
        return mg_price;
    }

    public void setMg_price(Integer mg_price) {
        this.mg_price = mg_price;
    }

    public Integer getChanStatus() {
        return chanStatus;
    }

    public void setChanStatus(Integer chanStatus) {
        this.chanStatus = chanStatus;
    }

    public java.util.Date getAddtime() {
        return addtime;
    }

    public void setAddtime(java.util.Date addtime) {
        this.addtime = addtime;
    }

    public java.util.Date getUpdatetime() {
        return updatetime;
    }

    public void setUpdatetime(java.util.Date updatetime) {
        this.updatetime = updatetime;
    }

}
