package com.ys.data.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table mcparams.
 */
public class McParamsBean {

    private Long mp_id;
    private String p_code;
    private String mcp_pvalue;

    public McParamsBean() {
    }

    public McParamsBean(Long mp_id) {
        this.mp_id = mp_id;
    }

    public McParamsBean(Long mp_id, String p_code, String mcp_pvalue) {
        this.mp_id = mp_id;
        this.p_code = p_code;
        this.mcp_pvalue = mcp_pvalue;
    }

    public Long getMp_id() {
        return mp_id;
    }

    public void setMp_id(Long mp_id) {
        this.mp_id = mp_id;
    }

    public String getP_code() {
        return p_code;
    }

    public void setP_code(String p_code) {
        this.p_code = p_code;
    }

    public String getMcp_pvalue() {
        return mcp_pvalue;
    }

    public void setMcp_pvalue(String mcp_pvalue) {
        this.mcp_pvalue = mcp_pvalue;
    }

}
