package com.ys.data.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table mcstatus.
 */
public class McStatusBean {

    private Integer mr_id;
    private String mc_no;
    private String mr_coin_status;
    private String mr_coin_short;
    private String mr_bill_status;
    private String mr_bill_short;
    private String mr_uppos_status;
    private String mr_scpos_status;
    private String mr_net_status;
    private String mr_temp;
    private String mr_door_isfault;
    private String mr_door_status;
    private Integer mr_chann_fault_num;
    private String mr_chann_fault_nos;
    private Integer mr_nogd_chnum;
    private String mr_nogd_chann;
    private Integer mr_gear_fault_num;
    private String mr_gear_fault_nos;
    private Integer mr_data_fault;
    private java.util.Date mr_door_date;
    private java.util.Date addtime;
    private java.util.Date updatetime;

    public McStatusBean() {
    }

    public McStatusBean(Integer mr_id) {
        this.mr_id = mr_id;
    }

    public McStatusBean(Integer mr_id, String mc_no, String mr_coin_status, String mr_coin_short, String mr_bill_status, String mr_bill_short, String mr_uppos_status, String mr_scpos_status, String mr_net_status, String mr_temp, String mr_door_isfault, String mr_door_status, Integer mr_chann_fault_num, String mr_chann_fault_nos, Integer mr_nogd_chnum, String mr_nogd_chann, Integer mr_gear_fault_num, String mr_gear_fault_nos, Integer mr_data_fault, java.util.Date mr_door_date, java.util.Date addtime, java.util.Date updatetime) {
        this.mr_id = mr_id;
        this.mc_no = mc_no;
        this.mr_coin_status = mr_coin_status;
        this.mr_coin_short = mr_coin_short;
        this.mr_bill_status = mr_bill_status;
        this.mr_bill_short = mr_bill_short;
        this.mr_uppos_status = mr_uppos_status;
        this.mr_scpos_status = mr_scpos_status;
        this.mr_net_status = mr_net_status;
        this.mr_temp = mr_temp;
        this.mr_door_isfault = mr_door_isfault;
        this.mr_door_status = mr_door_status;
        this.mr_chann_fault_num = mr_chann_fault_num;
        this.mr_chann_fault_nos = mr_chann_fault_nos;
        this.mr_nogd_chnum = mr_nogd_chnum;
        this.mr_nogd_chann = mr_nogd_chann;
        this.mr_gear_fault_num = mr_gear_fault_num;
        this.mr_gear_fault_nos = mr_gear_fault_nos;
        this.mr_data_fault = mr_data_fault;
        this.mr_door_date = mr_door_date;
        this.addtime = addtime;
        this.updatetime = updatetime;
    }

    public Integer getMr_id() {
        return mr_id;
    }

    public void setMr_id(Integer mr_id) {
        this.mr_id = mr_id;
    }

    public String getMc_no() {
        return mc_no;
    }

    public void setMc_no(String mc_no) {
        this.mc_no = mc_no;
    }

    public String getMr_coin_status() {
        return mr_coin_status;
    }

    public void setMr_coin_status(String mr_coin_status) {
        this.mr_coin_status = mr_coin_status;
    }

    public String getMr_coin_short() {
        return mr_coin_short;
    }

    public void setMr_coin_short(String mr_coin_short) {
        this.mr_coin_short = mr_coin_short;
    }

    public String getMr_bill_status() {
        return mr_bill_status;
    }

    public void setMr_bill_status(String mr_bill_status) {
        this.mr_bill_status = mr_bill_status;
    }

    public String getMr_bill_short() {
        return mr_bill_short;
    }

    public void setMr_bill_short(String mr_bill_short) {
        this.mr_bill_short = mr_bill_short;
    }

    public String getMr_uppos_status() {
        return mr_uppos_status;
    }

    public void setMr_uppos_status(String mr_uppos_status) {
        this.mr_uppos_status = mr_uppos_status;
    }

    public String getMr_scpos_status() {
        return mr_scpos_status;
    }

    public void setMr_scpos_status(String mr_scpos_status) {
        this.mr_scpos_status = mr_scpos_status;
    }

    public String getMr_net_status() {
        return mr_net_status;
    }

    public void setMr_net_status(String mr_net_status) {
        this.mr_net_status = mr_net_status;
    }

    public String getMr_temp() {
        return mr_temp;
    }

    public void setMr_temp(String mr_temp) {
        this.mr_temp = mr_temp;
    }

    public String getMr_door_isfault() {
        return mr_door_isfault;
    }

    public void setMr_door_isfault(String mr_door_isfault) {
        this.mr_door_isfault = mr_door_isfault;
    }

    public String getMr_door_status() {
        return mr_door_status;
    }

    public void setMr_door_status(String mr_door_status) {
        this.mr_door_status = mr_door_status;
    }

    public Integer getMr_chann_fault_num() {
        return mr_chann_fault_num;
    }

    public void setMr_chann_fault_num(Integer mr_chann_fault_num) {
        this.mr_chann_fault_num = mr_chann_fault_num;
    }

    public String getMr_chann_fault_nos() {
        return mr_chann_fault_nos;
    }

    public void setMr_chann_fault_nos(String mr_chann_fault_nos) {
        this.mr_chann_fault_nos = mr_chann_fault_nos;
    }

    public Integer getMr_nogd_chnum() {
        return mr_nogd_chnum;
    }

    public void setMr_nogd_chnum(Integer mr_nogd_chnum) {
        this.mr_nogd_chnum = mr_nogd_chnum;
    }

    public String getMr_nogd_chann() {
        return mr_nogd_chann;
    }

    public void setMr_nogd_chann(String mr_nogd_chann) {
        this.mr_nogd_chann = mr_nogd_chann;
    }

    public Integer getMr_gear_fault_num() {
        return mr_gear_fault_num;
    }

    public void setMr_gear_fault_num(Integer mr_gear_fault_num) {
        this.mr_gear_fault_num = mr_gear_fault_num;
    }

    public String getMr_gear_fault_nos() {
        return mr_gear_fault_nos;
    }

    public void setMr_gear_fault_nos(String mr_gear_fault_nos) {
        this.mr_gear_fault_nos = mr_gear_fault_nos;
    }

    public Integer getMr_data_fault() {
        return mr_data_fault;
    }

    public void setMr_data_fault(Integer mr_data_fault) {
        this.mr_data_fault = mr_data_fault;
    }

    public java.util.Date getMr_door_date() {
        return mr_door_date;
    }

    public void setMr_door_date(java.util.Date mr_door_date) {
        this.mr_door_date = mr_door_date;
    }

    public java.util.Date getAddtime() {
        return addtime;
    }

    public void setAddtime(java.util.Date addtime) {
        this.addtime = addtime;
    }

    public java.util.Date getUpdatetime() {
        return updatetime;
    }

    public void setUpdatetime(java.util.Date updatetime) {
        this.updatetime = updatetime;
    }

}
