package com.ys.data.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table promotion.
 */
public class PromotionBean {

    private Long pt_id;
    private String pt_name;
    private String pt_msg;
    private String pt_desc;
    private String pt_status;
    private String pt_starttime;
    private String pt_endtime;
    private String pt_range;
    private String pt_rangeparam;
    private String pt_goods;
    private String pt_goodsparam;
    private String pt_condition;
    private String pt_conditionparam;
    private String pt_type;
    private String pt_typeparam;
    private String remark;
    private String addtime;
    private String updatetime;

    public PromotionBean() {
    }

    public PromotionBean(Long pt_id) {
        this.pt_id = pt_id;
    }

    public PromotionBean(Long pt_id, String pt_name, String pt_msg, String pt_desc, String pt_status, String pt_starttime, String pt_endtime, String pt_range, String pt_rangeparam, String pt_goods, String pt_goodsparam, String pt_condition, String pt_conditionparam, String pt_type, String pt_typeparam, String remark, String addtime, String updatetime) {
        this.pt_id = pt_id;
        this.pt_name = pt_name;
        this.pt_msg = pt_msg;
        this.pt_desc = pt_desc;
        this.pt_status = pt_status;
        this.pt_starttime = pt_starttime;
        this.pt_endtime = pt_endtime;
        this.pt_range = pt_range;
        this.pt_rangeparam = pt_rangeparam;
        this.pt_goods = pt_goods;
        this.pt_goodsparam = pt_goodsparam;
        this.pt_condition = pt_condition;
        this.pt_conditionparam = pt_conditionparam;
        this.pt_type = pt_type;
        this.pt_typeparam = pt_typeparam;
        this.remark = remark;
        this.addtime = addtime;
        this.updatetime = updatetime;
    }

    public Long getPt_id() {
        return pt_id;
    }

    public void setPt_id(Long pt_id) {
        this.pt_id = pt_id;
    }

    public String getPt_name() {
        return pt_name;
    }

    public void setPt_name(String pt_name) {
        this.pt_name = pt_name;
    }

    public String getPt_msg() {
        return pt_msg;
    }

    public void setPt_msg(String pt_msg) {
        this.pt_msg = pt_msg;
    }

    public String getPt_desc() {
        return pt_desc;
    }

    public void setPt_desc(String pt_desc) {
        this.pt_desc = pt_desc;
    }

    public String getPt_status() {
        return pt_status;
    }

    public void setPt_status(String pt_status) {
        this.pt_status = pt_status;
    }

    public String getPt_starttime() {
        return pt_starttime;
    }

    public void setPt_starttime(String pt_starttime) {
        this.pt_starttime = pt_starttime;
    }

    public String getPt_endtime() {
        return pt_endtime;
    }

    public void setPt_endtime(String pt_endtime) {
        this.pt_endtime = pt_endtime;
    }

    public String getPt_range() {
        return pt_range;
    }

    public void setPt_range(String pt_range) {
        this.pt_range = pt_range;
    }

    public String getPt_rangeparam() {
        return pt_rangeparam;
    }

    public void setPt_rangeparam(String pt_rangeparam) {
        this.pt_rangeparam = pt_rangeparam;
    }

    public String getPt_goods() {
        return pt_goods;
    }

    public void setPt_goods(String pt_goods) {
        this.pt_goods = pt_goods;
    }

    public String getPt_goodsparam() {
        return pt_goodsparam;
    }

    public void setPt_goodsparam(String pt_goodsparam) {
        this.pt_goodsparam = pt_goodsparam;
    }

    public String getPt_condition() {
        return pt_condition;
    }

    public void setPt_condition(String pt_condition) {
        this.pt_condition = pt_condition;
    }

    public String getPt_conditionparam() {
        return pt_conditionparam;
    }

    public void setPt_conditionparam(String pt_conditionparam) {
        this.pt_conditionparam = pt_conditionparam;
    }

    public String getPt_type() {
        return pt_type;
    }

    public void setPt_type(String pt_type) {
        this.pt_type = pt_type;
    }

    public String getPt_typeparam() {
        return pt_typeparam;
    }

    public void setPt_typeparam(String pt_typeparam) {
        this.pt_typeparam = pt_typeparam;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getAddtime() {
        return addtime;
    }

    public void setAddtime(String addtime) {
        this.addtime = addtime;
    }

    public String getUpdatetime() {
        return updatetime;
    }

    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime;
    }

}
