package com.ys.data.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table salelist.
 */
public class SaleListBean {

    private Long sl_id;
    private String sl_no;
    private String sl_batch_no;
    private String sl_time;
    private String mc_no;
    private String sl_gd_no;
    private String sl_gd_name;
    private Long sl_pre_price;
    private Long sl_disc_price;
    private Long sl_vip_price;
    private Long sl_amt;
    private Long sl_score;
    private Long sl_cash_in;
    private Long sl_cash_out;
    private String sl_coin_in;
    private String sl_coin_out;
    private String sl_chann;
    private Long sl_num;
    private String sl_type;
    private String sl_isvip = "0";
    private String sl_err_msg;
    private String sl_acc_no;
    private Long sl_bf_amt;
    private Long sl_af_amt;
    private Long sl_send_status;
    private String sl_pay_status;
    private String sl_out_status;

    public SaleListBean() {
    }

    public SaleListBean(Long sl_id) {
        this.sl_id = sl_id;
    }

    public SaleListBean(Long sl_id, String sl_no, String sl_batch_no, String sl_time, String mc_no, String sl_gd_no, String sl_gd_name, Long sl_pre_price, Long sl_disc_price, Long sl_vip_price, Long sl_amt, Long sl_score, Long sl_cash_in, Long sl_cash_out, String sl_coin_in, String sl_coin_out, String sl_chann, Long sl_num, String sl_type, String sl_isvip, String sl_err_msg, String sl_acc_no, Long sl_bf_amt, Long sl_af_amt, Long sl_send_status, String sl_pay_status, String sl_out_status) {
        this.sl_id = sl_id;
        this.sl_no = sl_no;
        this.sl_batch_no = sl_batch_no;
        this.sl_time = sl_time;
        this.mc_no = mc_no;
        this.sl_gd_no = sl_gd_no;
        this.sl_gd_name = sl_gd_name;
        this.sl_pre_price = sl_pre_price;
        this.sl_disc_price = sl_disc_price;
        this.sl_vip_price = sl_vip_price;
        this.sl_amt = sl_amt;
        this.sl_score = sl_score;
        this.sl_cash_in = sl_cash_in;
        this.sl_cash_out = sl_cash_out;
        this.sl_coin_in = sl_coin_in;
        this.sl_coin_out = sl_coin_out;
        this.sl_chann = sl_chann;
        this.sl_num = sl_num;
        this.sl_type = sl_type;
        this.sl_isvip = sl_isvip;
        this.sl_err_msg = sl_err_msg;
        this.sl_acc_no = sl_acc_no;
        this.sl_bf_amt = sl_bf_amt;
        this.sl_af_amt = sl_af_amt;
        this.sl_send_status = sl_send_status;
        this.sl_pay_status = sl_pay_status;
        this.sl_out_status = sl_out_status;
    }

    public Long getSl_id() {
        return sl_id;
    }

    public void setSl_id(Long sl_id) {
        this.sl_id = sl_id;
    }

    public String getSl_no() {
        return sl_no;
    }

    public void setSl_no(String sl_no) {
        this.sl_no = sl_no;
    }

    public String getSl_batch_no() {
        return sl_batch_no;
    }

    public void setSl_batch_no(String sl_batch_no) {
        this.sl_batch_no = sl_batch_no;
    }

    public String getSl_time() {
        return sl_time;
    }

    public void setSl_time(String sl_time) {
        this.sl_time = sl_time;
    }

    public String getMc_no() {
        return mc_no;
    }

    public void setMc_no(String mc_no) {
        this.mc_no = mc_no;
    }

    public String getSl_gd_no() {
        return sl_gd_no;
    }

    public void setSl_gd_no(String sl_gd_no) {
        this.sl_gd_no = sl_gd_no;
    }

    public String getSl_gd_name() {
        return sl_gd_name;
    }

    public void setSl_gd_name(String sl_gd_name) {
        this.sl_gd_name = sl_gd_name;
    }

    public Long getSl_pre_price() {
        return sl_pre_price;
    }

    public void setSl_pre_price(Long sl_pre_price) {
        this.sl_pre_price = sl_pre_price;
    }

    public Long getSl_disc_price() {
        return sl_disc_price;
    }

    public void setSl_disc_price(Long sl_disc_price) {
        this.sl_disc_price = sl_disc_price;
    }

    public Long getSl_vip_price() {
        return sl_vip_price;
    }

    public void setSl_vip_price(Long sl_vip_price) {
        this.sl_vip_price = sl_vip_price;
    }

    public Long getSl_amt() {
        return sl_amt;
    }

    public void setSl_amt(Long sl_amt) {
        this.sl_amt = sl_amt;
    }

    public Long getSl_score() {
        return sl_score;
    }

    public void setSl_score(Long sl_score) {
        this.sl_score = sl_score;
    }

    public Long getSl_cash_in() {
        return sl_cash_in;
    }

    public void setSl_cash_in(Long sl_cash_in) {
        this.sl_cash_in = sl_cash_in;
    }

    public Long getSl_cash_out() {
        return sl_cash_out;
    }

    public void setSl_cash_out(Long sl_cash_out) {
        this.sl_cash_out = sl_cash_out;
    }

    public String getSl_coin_in() {
        return sl_coin_in;
    }

    public void setSl_coin_in(String sl_coin_in) {
        this.sl_coin_in = sl_coin_in;
    }

    public String getSl_coin_out() {
        return sl_coin_out;
    }

    public void setSl_coin_out(String sl_coin_out) {
        this.sl_coin_out = sl_coin_out;
    }

    public String getSl_chann() {
        return sl_chann;
    }

    public void setSl_chann(String sl_chann) {
        this.sl_chann = sl_chann;
    }

    public Long getSl_num() {
        return sl_num;
    }

    public void setSl_num(Long sl_num) {
        this.sl_num = sl_num;
    }

    public String getSl_type() {
        return sl_type;
    }

    public void setSl_type(String sl_type) {
        this.sl_type = sl_type;
    }

    public String getSl_isvip() {
        return sl_isvip;
    }

    public void setSl_isvip(String sl_isvip) {
        this.sl_isvip = sl_isvip;
    }

    public String getSl_err_msg() {
        return sl_err_msg;
    }

    public void setSl_err_msg(String sl_err_msg) {
        this.sl_err_msg = sl_err_msg;
    }

    public String getSl_acc_no() {
        return sl_acc_no;
    }

    public void setSl_acc_no(String sl_acc_no) {
        this.sl_acc_no = sl_acc_no;
    }

    public Long getSl_bf_amt() {
        return sl_bf_amt;
    }

    public void setSl_bf_amt(Long sl_bf_amt) {
        this.sl_bf_amt = sl_bf_amt;
    }

    public Long getSl_af_amt() {
        return sl_af_amt;
    }

    public void setSl_af_amt(Long sl_af_amt) {
        this.sl_af_amt = sl_af_amt;
    }

    public Long getSl_send_status() {
        return sl_send_status;
    }

    public void setSl_send_status(Long sl_send_status) {
        this.sl_send_status = sl_send_status;
    }

    public String getSl_pay_status() {
        return sl_pay_status;
    }

    public void setSl_pay_status(String sl_pay_status) {
        this.sl_pay_status = sl_pay_status;
    }

    public String getSl_out_status() {
        return sl_out_status;
    }

    public void setSl_out_status(String sl_out_status) {
        this.sl_out_status = sl_out_status;
    }

    @Override
    public String toString() {
        return "SaleListBean{" +
                "sl_id=" + sl_id +
                ", sl_no='" + sl_no + '\'' +
                ", sl_send_status=" + sl_send_status +
                ", sl_pay_status='" + sl_pay_status + '\'' +
                ", sl_out_status='" + sl_out_status + '\'' +
                '}';
    }
}
